#
# This is free software, lisence use MIT.
#

name: twrp-mh2lm

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 30 19 * * *

env:
  REPO_URL: https://github.com/Lionalbyron/twrp_mh2lm
  REPO_BRANCH: master
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: false
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
  TZ: Asia/Shanghai
  
jobs:

  merge:

    runs-on: ubuntu-latest

    steps:

    - name: apt update
      run : |
        pwd
        sudo apt update
        sudo apt install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev git python3 python
        
    - name: repo
      run : |
        pwd
        mkdir -p ~/bin
        curl https://mirrors.tuna.tsinghua.edu.cn/git/git-repo > ~/bin/repo
        pwd
        sudo cp ~/bin/repo /bin/repo
        sudo chmod a+x /bin/repo
        export REPO_URL='https://mirrors.tuna.tsinghua.edu.cn/git/git-repo'
    - name: config  global url
      run : | 
        git config --global url.https://mirrors.bfsu.edu.cn/git/AOSP/.insteadof https://android.googlesource.com/
        pwd
    - name: get device
      run: |
        pwd
#        git clone https://github.com/Lionalbyron/twrp_mh2lm
    - name: repo sync
      run: |
        mkdir twrp
        cd twrp
        ls
        git config --global http.sslverify false
        git config --global https.sslverify false      
#        repo init --depth=1 -u
#		git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
#        repo sync
        ls
        sudo cp -R ../twrp_mh2lm/device/* ./device
        ls
        ls device
        ls device/lge
        ls device/lge/mh2lm
        ls device/lge/mh2lm/prebuit
